### ISSUE TITLE
(after upgrading from 2.21.3 to 2.21.4) ImportError: cannot import name bh_support

### ISSUE THREAD

**Issue by darkred** [facelessuser/BracketHighlighter#364]
Just upgrading BH from 2.21.3 to 2.21.4 ) _(using ST3 build 3120 x64 in win10 x64)_
I get this in console every time I launch ST3:

```
reloading plugin BracketHighlighter.bh_core
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 892, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "bh_core in C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Installed Packages\BracketHighlighter.sublime-package", line 20, in <module>
ImportError: cannot import name bh_support
```

I also tried pressing `Satisfy Dependencies` 
as well as removing and re-installing the package via Package Control, 
but it didn't help.

**Comment by facelessuser** [comment]
Yeah...I messed up.  Give me a sec to fix it.

**Comment by facelessuser** [comment]
Sorry about that.  New release: https://github.com/facelessuser/BracketHighlighter/releases/tag/st3-2.21.5.

**Comment by darkred** [comment]
No problem.
I confirm it's fixed.
Thank you
